version: 2.1

description: |
  Docker image releaser orb based on circleci/docker

orbs:
  aws: circleci/aws-cli@0.1.17
  circleci-docker: circleci/docker@0.5.18

#examples:
#  release:
#    description: Release a helm chart to chartmuseum
#    usage:
#      version: 2.1
#
#      orbs:
#        helm: banzaicloud/helm@v0.0.4
#
#      workflows:
#        helm-chart-lint:
#          jobs:
#            - helm/lint-chart:
#                charts-dir: charts
#                filters:
#                  tags:
#                    ignore: /.*/
#        helm-chart-release:
#          jobs:
#            - helm/publish-chart:
#                context: helm
#                charts-dir: charts
#                filters:
#                  branches:
#                    ignore: /.*/
#                  tags:
#                    only: /chart\/logging-operator\/\d+.\d+.\d+/

executors:
  machine:
    description: |
      Machine executor
    machine:
      docker_layer_caching: false
      image: ubuntu-1604:201903-01
  machine-dlc:
    description: |
      Machine executor with DLC enabled
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01

commands:
  setup-aws-cli:
    description: Setup aws-cli
    steps:
      - aws/install
      - aws/setup

  login:
    description: Docker login
    steps:
      - circleci-docker/check

  ecr-login:
    description: Login to Amazon ECR
    parameters:
      region:
        description: AWS region
        default: ${AWS_DEFAULT_REGION}
        type: string
    steps:
      - run:
          name: ECR login
          command: |
            $(aws ecr get-login --no-include-email --region <<parameters.region>>)

  tag:
    description: Tag image
    parameters:
      registry:
        default: docker.io
        description: Name of registry to use, defaults to docker.io
        type: string
      image:
        description: Name of image to tag
        type: string
      source-tag:
        default: ${CIRCLE_SHA1}
        description: Source tag
        type: string
      target-tag:
        default: ${CIRCLE_TAG}
        description: Target tag
        type: string
    steps:
      - run:
          name: Tag image
          command: |
            docker tag \
              <<parameters.registry>>/<<parameters.image>>:<<parameters.source-tag>> \
              <<parameters.registry>>/<<parameters.image>>:<<parameters.target-tag>>

  version-check:
    description: Check if version is stable
    parameters:
      version:
        description: Version to check
        type: string
      stable-version-pattern:
        default: '^[0-9]+\.[0-9]+\.[0-9]+$'
        description: Version pattern to check
        type: string
      halt:
        default: true
        description: Halt job when version is unstable
        type: boolean
      result-variable:
        default: STABLE_VERSION
        description: Environment variable name to store result
        type: string
    steps:
     - unless:
         condition: <<parameters.halt>>
         steps:
          - run:
              name: Check version stability
              command: |
                if echo "<<parameters.version>>" | grep -Eq '<<parameters.stable-version-pattern>>'; then
                  echo "export <<parameters.result-variable>>='true'" >> $BASH_ENV
                else
                  echo 'Unstable version.'
                  echo "export <<parameters.result-variable>>='false'" >> $BASH_ENV
                fi
     - when:
         condition: <<parameters.halt>>
         steps:
          - run:
              name: Check version stability
              command: |
                if ! echo "<<parameters.version>>" | grep -Eq '<<parameters.stable-version-pattern>>'; then
                  echo 'Unstable version. Skipping further steps.'
                  circleci-agent step halt
                fi

  push:
    description: Publish image conditionally
    parameters:
      registry:
        default: docker.io
        description: name of registry to use, defaults to docker.io
        type: string
      image:
        description: Image name
        type: string
      tag:
        default: ${CIRCLE_TAG}
        description: Image tag
        type: string
    steps:
      - run:
          name: Publish
          command: |
            docker push <<parameters.registry>>/<<parameters.image>>:<<parameters.tag>>

  conditional-push:
    description: Publish image conditionally
    parameters:
      registry:
        default: docker.io
        description: name of registry to use, defaults to docker.io
        type: string
      image:
        description: Image name
        type: string
      tag:
        default: ${CIRCLE_TAG}
        description: Image tag
        type: string
      condition-steps:
        type: steps
        description: asdf
      result-variable:
        default: STABLE_VERSION
        description: Name of environment variable containing result of condition step(s)
        type: string
    steps:
      - steps: <<parameters.condition-steps>>
      - run:
          name: Publish
          command: |
              if [ "${<<parameters.result-variable>>}" = "true" ]; then
                docker push <<parameters.registry>>/<<parameters.image>>:<<parameters.tag>>
              fi

jobs:
  build:
    executor: <<parameters.executor>>
    parameters:
      registry:
        default: docker.io
        description: name of registry to use, defaults to docker.io
        type: string
      image:
        description: name of image to tag
        type: string
      tag:
        default: ${CIRCLE_SHA1}
        description: Image tag
        type: string
      extra-build-args:
        default: ''
        description: Extra flags to pass to docker build
        type: string
      build-context-path:
        default: .
        description: Path to the directory containing your Dockerfile and build context
        type: string
      dockerfile:
        description: Name of dockerfile to use
        default: Dockerfile
        type: string
      executor:
        default: docker/machine
        description: Executor to use
        type: executor
    steps:
      - checkout
      - circleci-docker/build:
          registry: <<parameters.registry>>
          image: <<parameters.image>>
          tag: <<parameters.tag>>
          extra_build_args: <<parameters.extra-build-args>>
          path: <<parameters.build-context-path>>
          dockerfile: <<parameters.dockerfile>>

  publish:
    executor: <<parameters.executor>>
    parameters:
      registry:
        default: docker.io
        description: name of registry to use, defaults to docker.io
        type: string
      image:
        description: name of image to tag
        type: string
      tag:
        default: ${CIRCLE_TAG}
        description: source tag
        type: string
      latest:
        description: Publish latest tag
        default: false
        type: boolean
      latest-tag:
        description: Custom latest tag, e.g. latest-eks
        default: latest
        type: string
      stable-version-pattern:
        default: '^[0-9]+\.[0-9]+\.[0-9]+$'
        description: Version pattern to check before publishing latest tag
        type: string
      extra-build-args:
        default: ''
        description: Extra flags to pass to docker build
        type: string
      build-context-path:
        default: .
        description: Path to the directory containing your Dockerfile and build context
        type: string
      dockerfile:
        default: Dockerfile
        description: 'Name of dockerfile to use, defaults to Dockerfile'
        type: string
      after-checkout:
        default: []
        description: Optional steps to run after checkout
        type: steps
      tag-steps:
        default: []
        description: Override tag steps
        type: steps
      push-steps:
        default: []
        description: Override push steps
        type: steps
      login:
        default: []
        description: Custom login steps
        type: steps
      executor:
        default: docker/machine
        description: Executor to use
        type: executor
    steps:
      - checkout
      - when:
          condition: <<parameters.after-checkout>>
          name: Steps to run after checkout
          steps: <<parameters.after-checkout>>
      - when:
          condition: <<parameters.login>>
          name: Run custom login
          steps: <<parameters.login>>
      - unless:
          condition: <<parameters.login>>
          name: Login to DockerHub
          steps:
            - login
      - circleci-docker/build:
          registry: <<parameters.registry>>
          image: <<parameters.image>>
          extra_build_args: <<parameters.extra-build-args>>
          path: <<parameters.build-context-path>>
          dockerfile: <<parameters.dockerfile>>
      - when:
          condition: <<parameters.tag-steps>>
          name: Tag steps
          steps: <<parameters.tag-steps>>
      - unless:
          condition: <<parameters.tag-steps>>
          name: Tag images
          steps:
            - tag:
                registry: <<parameters.registry>>
                image: <<parameters.image>>
                target-tag: <<parameters.tag>>
            - when:
                condition: <<parameters.latest>>
                name: Tag latest
                steps:
                  - tag:
                      registry: <<parameters.registry>>
                      image: <<parameters.image>>
                      target-tag: <<parameters.tag>>
      - when:
          condition: <<parameters.push-steps>>
          name: Push steps
          steps: <<parameters.push-steps>>
      - unless:
          condition: <<parameters.push-steps>>
          name: Push images
          steps:
            - push:
                registry: <<parameters.registry>>
                image: <<parameters.image>>
                tag: <<parameters.tag>>
            - when:
                condition: <<parameters.latest>>
                name: Push latest tag
                steps:
                  - conditional-push:
                      registry: <<parameters.registry>>
                      image: <<parameters.image>>
                      tag: <<parameters.latest-tag>>
                      condition-steps:
                        - version-check:
                            halt: false
                            version: ${CIRCLE_TAG}
                            stable-version-pattern: <<parameters.stable-version-pattern>>
